name: Songsterr
options:
  bundleIdPrefix: com.songsterr
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  Songsterr:
    type: application
    platform: iOS
    sources:
      - path: Songsterr/Sources
      - path: Songsterr/Resources
    settings:
      base:
        INFOPLIST_FILE: Songsterr/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.songsterr.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
